indexedsearch:
  targetPid: 3
fcbigfoot:
  pages:
    privacy: 2
    contact: 4
  socialmedia:
    channels:
      instagram:
        link: 'https://www.instagram.com/typo3_official/'
waveCart:
  cartPid: 102
  cartItemsPid: 102
  orderPid: 102
  orderItemsPid: 102
  cartPageId: 102
  cartItemPid: 102
